site_name: CasTECHdefels 2026. Projectes connectats al núvol... amb el soldador a la mà.
site_description: Guia de pràctiques i exemples de programació amb dificultat creixent.
site_author: Marcos Quílez

theme:
  name: material
  language: ca # Configura la interfaz de la web en catalán (botones de búsqueda, siguiente, etc.)
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Canvia a mode fosc
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Canvia a mode clar
  features:
    - navigation.tabs # Menú superior per a les grans seccions
    - navigation.sections # Menú lateral organitzat per blocs
    - content.code.copy # Botó per copiar el codi
    - toc.integrate # Mou l'índex de la dreta al menú de l'esquerra

plugins:
  - search # Activa el buscador automático dentro de la web

# --- AQUÍ DEFINES EL ORDEN Y LA ESTRUCTURA DEL MENÚ ---
nav:
  - Benvinguda: index.md
  
  - Bloc 1:
    - Introducció i presa de contacte: contacte.md
    - Bola extra, repte avançat: extra1.md

  - Bloc 2:
    - Taller de soldadura: soldadura.md
    - LED, sortida digital: led_digital.md
    - LED, sortida analògica (PWM): led_analogic_PWM.md
    #- Introducció a les pantalles OLED: pantalles_oled.md
    #- Gràfics a la pantalla OLED: grafics_oled.md
    #- Bola extra, repte avançat: extra2.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
