site_name: Curs d'Arduino. La meva Mascota Robòtica
site_description: Guia de pràctiques i exemples de programació amb dificultat creixent.
site_author: El teu Nom

theme:
  name: material
  language: ca # Configura la interfaz de la web en catalán (botones de búsqueda, siguiente, etc.)
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Canvia a mode fosc
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Canvia a mode clar
  features:
    - navigation.tabs # Menú superior para las grandes secciones
    - navigation.sections # Menú lateral organizado por bloques
    - content.code.copy # Botón para que los alumnos puedan copiar el código fácilmente

plugins:
  - search # Activa el buscador automático dentro de la web

# --- AQUÍ DEFINES EL ORDEN Y LA ESTRUCTURA DEL MENÚ ---
nav:
  - Benvinguda: index.md
  
  - Actuadors i Sortides:
    - LED Digital (El Batec): led_digital.md
    - LED Analògic (PWM): led_analogic_PWM.md
    - Efecte Respiració: led_respiracio.md
    # En el futuro, si añades un zumbador, solo creas "brunzidor.md" y lo pones aquí:
    # - Brunzidors i Sons: brunzidor.md

  - Visualització:
    - Introducció a les pantalles OLED: pantalles_oled.md
    - Disseny de gràfics i icones: oled_grafics.md

  - Sensors i Comunicació I2C:
    - Com funciona el bus I2C?: bus_i2c.md
    - Lectura de sensors ambientals: sensors_ambientals.md

  - Connectivitat i IoT:
    - Configuració Wi-Fi: connexio_wifi.md
    - Creació d'un Bot de Telegram: bot_telegram.md
    - Alertes de la mascota: telegram_alertes.md